server:
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - argocd.loicgombeaud.com
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
    tls:
      - hosts:
        - argocd.loicgombeaud.com
        secretName: argocd-tls
  extraArgs:
    - --insecure
configs:
  cm:
    timeout.reconciliation: 10s
